<a href="https://colab.research.google.com/github/yesaswiniswarna/FML/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

NUMPY

In [1]:
import numpy as np

In [2]:
a = np.array([1, 2, 3])
print(type(a), a.shape, a[0], a[1], a[2])
a[0] = 5
print(a)

<class 'numpy.ndarray'> (3,) 1 2 3
[5 2 3]


In [3]:
b=np.array([[1,2,3],[4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [4]:
b[0]

array([1, 2, 3])

In [7]:
print(b.shape)
print(b[0,0],b[0,1],b[1,0])

(2, 3)
1 2 4


In [8]:
a=np.zeros((2,2))
print(a)

[[0. 0.]
 [0. 0.]]


In [9]:
b=np.ones((1,2))
print(b)

[[1. 1.]]


In [10]:
c=np.full((2,2),7)
print(c)

[[7 7]
 [7 7]]


In [11]:
d=np.eye(2)
print(d)

[[1. 0.]
 [0. 1.]]


In [12]:
e=np.random.random((2,2))
print(e)

[[0.23108156 0.75142863]
 [0.84539585 0.04478873]]


**array indexing**

In [13]:
import numpy as np
a=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
b=a[:2, 1:3]
print(b)

[[2 3]
 [6 7]]


In [14]:
print(a[0,1])
b[0,0]=77
print(a[0,1])

2
77


In [15]:
print(a)
print(b)

[[ 1 77  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[77  3]
 [ 6  7]]


In [17]:
a=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [19]:
row_r1=a[1, :]
row_r2=a[1:2, :]
row_r3=a[[1], :]
print(row_r1, row_r1.shape)
print(row_r2, row_r2.shape)
print(row_r3,row_r3.shape)

[5 6 7 8] (4,)
[[5 6 7 8]] (1, 4)
[[5 6 7 8]] (1, 4)


In [20]:
col_r1=a[:, 1]
col_r2=a[:, 1:2]
print(col_r1, col_r1.shape)
print()
print(col_r2, col_r2.shape)

[ 2  6 10] (3,)

[[ 2]
 [ 6]
 [10]] (3, 1)


In [23]:
a=np.array([[1,2], [3,4],[5,6]])
print(a.shape)
print(a[[0,1,2],[0,1,0]])
print(np.array([a[0,1], a[0,1]]))

(3, 2)
[1 4 5]
[2 2]


In [24]:
a=np.array([[1,2,3],[4,5,6], [7,8,9]])
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [25]:
b = np.array([0, 2, 0, 1])
print(b)
print(a[:, b])

[0 2 0 1]
[[1 3 1 2]
 [4 6 4 5]
 [7 9 7 8]]


In [28]:
import numpy as np

a = np.array([[1,2], [3, 4], [5, 6]])
print(a)

bool_idx = (a > 2)
print(bool_idx)

[[1 2]
 [3 4]
 [5 6]]
[[False False]
 [ True  True]
 [ True  True]]
